#!/bin/sh

################################################################################
# @author      : Tyler Dunneback (tylerdback@pm.me)
# @file        : awc
# @created     : Tue Aug 15 09:05:22 PM EDT 2023
#
# @description : A simple calculator written in awk for quick arithmetic in
#                the shell.
################################################################################

awk "BEGIN { print $* }"

# vim: ft=sh
