#!/usr/bin/env sh

################################################################################
# @author      : Tyler Dunneback (tylerdback@pm.me)
# @file        : mpc_up
# @created     : Tue Aug 15 09:06:27 PM EDT 2023
#
# @description : Quickly update an mpd playlist with mpc after adding new songs
#                to the music directory.
################################################################################

music_dir="$HOME/Media/Music/"
playlist_name="$1"

[ -d "$music_dir" ] && cd "$music_dir" || exit 1

# Don't forget to clear the current playlist, or else it gets duplicated
[ -e "$HOME/.config/mpd/playlists/${playlist_name}.m3u" ] && \
    mpc clear > /dev/null && \
    mpc rm "$playlist_name"

# Add every song in the music directory.
mpc add -- *

mpc save "$playlist_name"

# vim:ft=sh
