#!/bin/sh

# ==============================================================================
#
#   Author  : Tyler Dunneback
#   Date    : Aug 05, 2023
#   GitHub  : https://github.com/Tdback
#
#   Move a file to a specific directory, then go to that directory.
#
# ==============================================================================

if [ -d "$2" ]
then
    mv "$1" "$2" && cd "$2" || exit 1
else
    mv "$1" "$2"
fi

# vim: ft=sh
