#!/bin/sh

################################################################################
# @author      : Tyler Dunneback (tylerdback@pm.me)
# @file        : pkgs
# @created     : Tue Aug 15 05:27:41 PM EDT 2023
#
# @description : View the total number of installed packages via pacman.
################################################################################

pacman -Q | wc -l | xargs -I{} echo "Packages installed: {}"

# vim: ft=sh
