#!/bin/sh

# ==============================================================================
#
#   Author  : Tyler Dunneback
#   Date    : Aug 05, 2023
#   GitHub  : https://github.com/Tdback
#
#   Create a backup of all installed packages on the system.
#
# ==============================================================================

[ ! -d "$HOME"/.dotfiles/archlinux/ ] && mkdir "$HOME"/.dotfiles/archlinux/

pacman -Qqn >"$HOME"/.dotfiles/archlinux/pacmanlist
pacman -Qqm >"$HOME"/.dotfiles/archlinux/aurlist

# vim: ft=sh
