#!/bin/sh

################################################################################
# @author      : Tyler Dunneback (tylerdback@pm.me)
# @file        : save_packages
# @created     : Tue Aug 15 09:07:37 PM EDT 2023
#
# @description : Create a backup of all installed packages on the system.
################################################################################

[ ! -d "$HOME"/.dotfiles/archlinux/ ] && mkdir "$HOME"/.dotfiles/archlinux/

pacman -Qqn >"$HOME"/.dotfiles/archlinux/pacmanlist
pacman -Qqm >"$HOME"/.dotfiles/archlinux/aurlist

# vim: ft=sh
