#!/bin/sh

################################################################################
# @author      : Tyler Dunneback (tylerdback@pm.me)
# @file        : sbg
# @created     : Tue Aug 15 09:07:56 PM EDT 2023
#
# @description : Quick way to set the background on my system.
################################################################################

img_dir="$HOME"/.local/backgrounds/

[ "$1" = "-r" ] && feh --bg-scale --randomize "$img_dir" && exit 0

images=$(ls "$img_dir")

selected=$(echo "$images" | fzf)

[ -z "$selected" ] && exit 0

feh --bg-scale "$img_dir$selected"

# vim: ft=sh
