#!/bin/sh

# Alacritty
ln -sf ~/.dotfiles/.config/alacritty/alacritty.yml ~/.config/alacritty/ 

# Autostart
ln -sf ~/.dotfiles/.config/autostart/startup.sh ~/.config/autostart/startup.sh

# Bspwm
ln -sf ~/.dotfiles/.config/bspwm/bspwmrc ~/.config/bspwm/bspwmrc

# Lockscreen
ln -sf ~/.dotfiles/.config/betterlockscreenrc ~/.config/betterlockscreenrc 

# Polybar
ln -sf ~/.dotfiles/.config/polybar/config.ini ~/.config/polybar/config.ini 
ln -sf ~/.dotfiles/.config/polybar/launch.sh ~/.config/polybar/launch.sh 

# Rofi
ln -sf ~/.dotfiles/.config/rofi/config.rasi ~/.config/rofi/config.rasi 

# Starship
ln -sf ~/.dotfiles/.config/starship.toml ~/.config/starship.toml 

# Sxhkd
ln -sf ~/.dotfiles/.config/sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc 
