#!/usr/bin/awk -f

################################################################################
# @author      : Tyler Dunneback (tylerdback@pm.me)
# @file        : temp
# @created     : Fri Sep  8 04:11:40 PM EDT 2023
#
# @description : A quick and dirty temperature converter in awk.
################################################################################

BEGIN {
    temp = ARGV[1]

    if ( temp ~ /^.+C$/ ) { print (substr(temp, 1, length(temp) - 1) * \
                                   ( 9 / 5 )) + 32 "F" }

    else if ( temp ~ /^.+F$/ ) { print (substr(temp, 1, length(temp) - 1) - \
                                    32) * ( 5 / 9 ) "C" }

    else { print temp " is not a valid temperature!" }
}
