#!/bin/sh

################################################################################
# @author      : Tyler Dunneback (tylerdback@pm.me)
# @file        : weather
# @created     : Tue Aug 15 09:11:07 PM EDT 2023
#
# @description : Quick way to check the weather forecast.
################################################################################

default="kalamazoo"

city=$(echo "$1" | tr '+' ' ')
: "${city:=$default}"

curl -s "https://wttr.in/$city" | head -n -2
# vim: ft=sh
